# Playing with pedigrees

In [11]:
import msprime
import tskit
import numpy as np

In [4]:
nGens = 2
N = 500
samp = 1

In [6]:
np.array(range(0,2))

array([0, 1])

In [22]:
def genIndRange(gen, N):
    """
    Generate a range of possible parents depending on N and generation.
    """
    return np.array(range(gen*N, (gen+1)*N))

In [104]:
def parentIndOffset(N, nSamp):
    """
    Generate a range of parent id offsets (sampling with replacement
    """
    # random nums
    nums = np.random.choice(np.arange(N), nSamp, replace=True)
    print(nums)
    ss = set(nums)
    ids = np.zeros(len(nums), dtype=np.int32)
    c = 1
    for i in ss:
        
        ids[nums == i] = c
        c +=1
    return ids

In [107]:
parentIndOffset(N=500, nSamp=5)

[461 353  45 386 118]


array([4, 1, 3, 2, 5], dtype=int32)

In [110]:
np.array([],dtype=np.int32)

array([], dtype=int32)

In [111]:
def makePed(numG,N, nInds):
    """
    Make a pedigree by recurrently smapling parents from past generations
    """
    idCounter=0
    currrentT=0
    ids=np.array([],dtype=np.int32)
    t=np.array([],dtype=np.int32)
    mums=np.array([],dtype=np.int32)
    dads=np.array([],dtype=np.int32)
    for g in range(numG): # the generation loop

        if g > 0: # dont run in first gen
            nPrev = len(ids[t==(g-1)]) # ind in previous generation
            pp = parentIndOffset(N, nPrev) # parents of those inds
            
            
            
        else: #only in 1st gen
            
            
            for i in range(nInds):
                #sample parents...
                
                ids.append(idCounter)
                idCounter += 1
                t.append(currentT)
        # each generation
        currentT += 1
            
            
    
    

In [20]:
ped = msprime.PedigreeBuilder(individuals_metadata_schema=tskit.MetadataSchema.permissive_json())

In [21]:
ped

In [18]:
?ped.add_individual

Signature:
ped.add_individual(
    *,
    time,
    is_sample=None,
    parents=None,
    population=None,
    metadata=None,
) -> 'int'
Docstring:
Adds an individual with the specified properties, returning its ID.

:param float time: The time for this individual measured in generations ago.
:param bool is_sample: If True, the new individual is marked as a sample;
    if False, the individual is not marked as a sample. If None (the default)
    the individual is marked as a sample if its ``time`` is zero.
    Parent IDs are not checked, and may refer to individuals not yet
    added to the tables.
:param list(int) parents: The integer IDs of the specified individual's
    parents. Exactly two parents must be specified. If None (the default),
    the individual is treated as a founder by setting its parents to
    ``[-1, -1]``.
:param str|int population: The population to associated with this
    individual. The value can be a string or integer, following the
    usual
    :ref:`popula